export interface CurrencyInfo {
  code: string;
  name: string;
  symbol: string;
}

export const CURRENCIES_DATA: Record<string, CurrencyInfo> = {
  usd: { code: 'usd', name: 'US Dollar', symbol: '$' },
  aed: { code: 'aed', name: 'UAE Dirham', symbol: 'DH' },
  ars: { code: 'ars', name: 'Argentine Peso', symbol: '$' },
  aud: { code: 'aud', name: 'Australian Dollar', symbol: 'A$' },
  bdt: { code: 'bdt', name: 'Bangladeshi Taka', symbol: '৳' },
  bhd: { code: 'bhd', name: 'Bahraini Dinar', symbol: 'BD' },
  bmd: { code: 'bmd', name: 'Bermudian Dollar', symbol: '$' },
  brl: { code: 'brl', name: 'Brazil Real', symbol: 'R$' },
  cad: { code: 'cad', name: 'Canadian Dollar', symbol: 'C$' },
  chf: { code: 'chf', name: 'Swiss Franc', symbol: 'CHF' },
  clp: { code: 'clp', name: 'Chilean Peso', symbol: '$' },
  cny: { code: 'cny', name: 'Chinese Yuan', symbol: '¥' },
  czk: { code: 'czk', name: 'Czech Koruna', symbol: 'Kč' },
  dkk: { code: 'dkk', name: 'Danish Krone', symbol: 'kr' },
  eur: { code: 'eur', name: 'Euro', symbol: '€' },
  gbp: { code: 'gbp', name: 'British Pound', symbol: '£' },
  gel: { code: 'gel', name: 'Georgian Lari', symbol: '₾' },
  hkd: { code: 'hkd', name: 'Hong Kong Dollar', symbol: 'HK$' },
  huf: { code: 'huf', name: 'Hungarian Forint', symbol: 'Ft' },
  idr: { code: 'idr', name: 'Indonesian Rupiah', symbol: 'Rp' },
  ils: { code: 'ils', name: 'Israeli Shekel', symbol: '₪' },
  inr: { code: 'inr', name: 'Indian Rupee', symbol: '₹' },
  jpy: { code: 'jpy', name: 'Japanese Yen', symbol: '¥' },
  krw: { code: 'krw', name: 'South Korean Won', symbol: '₩' },
  kwd: { code: 'kwd', name: 'Kuwaiti Dinar', symbol: 'KD' },
  lkr: { code: 'lkr', name: 'Sri Lankan Rupee', symbol: 'Rs' },
  mmk: { code: 'mmk', name: 'Myanmar Kyat', symbol: 'K' },
  mxn: { code: 'mxn', name: 'Mexican Peso', symbol: '$' },
  myr: { code: 'myr', name: 'Malaysian Ringgit', symbol: 'RM' },
  ngn: { code: 'ngn', name: 'Nigerian Naira', symbol: '₦' },
  nok: { code: 'nok', name: 'Norwegian Krone', symbol: 'kr' },
  nzd: { code: 'nzd', name: 'New Zealand Dollar', symbol: '$' },
  php: { code: 'php', name: 'Philippine Peso', symbol: '₱' },
  pkr: { code: 'pkr', name: 'Pakistani Rupee', symbol: 'Rs' },
  pln: { code: 'pln', name: 'Polish Zloty', symbol: 'zł' },
  rub: { code: 'rub', name: 'Russian Ruble', symbol: '₽' },
  sar: { code: 'sar', name: 'Saudi Riyal', symbol: 'SR' },
  sek: { code: 'sek', name: 'Swedish Krona', symbol: 'kr' },
  sgd: { code: 'sgd', name: 'Singapore Dollar', symbol: 'S$' },
  thb: { code: 'thb', name: 'Thai Baht', symbol: '฿' },
  try: { code: 'try', name: 'Turkish Lira', symbol: '₺' },
  twd: { code: 'twd', name: 'Taiwan Dollar', symbol: 'NT$' },
  uah: { code: 'uah', name: 'Ukrainian Hryvnia', symbol: '₴' },
  vef: { code: 'vef', name: 'Venezuelan Bolívar', symbol: 'Bs.F' },
  vnd: { code: 'vnd', name: 'Vietnamese Dong', symbol: '₫' },
  zar: { code: 'zar', name: 'South African Rand', symbol: 'R' },
  xdr: { code: 'xdr', name: 'Special Drawing Rights', symbol: 'XDR' },
};
